// <auto-generated />
using System;
using AgorusApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgorusRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220927042815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("AgorusApi.Model.FileHistoryModel", b =>
                {
                    b.Property<int?>("FileHistoryModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("FileModelId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileHistoryModelId");

                    b.HasIndex("FileModelId");

                    b.HasIndex(new[] { "Date" }, "idxDate");

                    b.ToTable("FileHistories");
                });

            modelBuilder.Entity("AgorusApi.Model.FileModel", b =>
                {
                    b.Property<int?>("FileModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FileModelId");

                    b.HasIndex(new[] { "Name" }, "idxName")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AgorusApi.Model.FileHistoryModel", b =>
                {
                    b.HasOne("AgorusApi.Model.FileModel", "FileModel")
                        .WithMany("FileHistoryModels")
                        .HasForeignKey("FileModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileModel");
                });

            modelBuilder.Entity("AgorusApi.Model.FileModel", b =>
                {
                    b.Navigation("FileHistoryModels");
                });
#pragma warning restore 612, 618
        }
    }
}
